version: '3.0'

services:
  web:
    build: .
    container_name: flask_app
    command: python run.py
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    ports:
      - "5000:5000"